version: 1.0.{build}
before_build:
  - nuget restore
build:
  verbosity: minimal
after_test: 
    - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:.\SampleProject.Test\bin\Debug\SampleProject.Test.dll" -filter:"+[SampleProject]*  -[SampleProject]SampleProject.Properties.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\SampleProject_coverage.xml
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "SampleProject_coverage.xml"